# Give Me Some Credit

Predict the probability that somebody will experience financial distress in the next two years.

# Introduction

How to build a classification model to predict the probability that somebody will experience financial distress in the next two years.

Improve on the state of the art in credit scoring by predicting the probability that somebody will experience financial distress in the next two years.

Banks play a crucial role in market economies.
They decide who can get finance and on what terms and can make or break investment decisions. For markets and society to function, individuals and companies need access to credit.

Credit scoring algorithms, which make a guess at the probability of default, are the methods banks use to determine whether or not a loan should be granted by predicting the probability that somebody will experience financial distress in the next two years.

The goal is to build a model that can be used to help make the best financial decisions.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mirela\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.15.4 in c:\users\mirela\anaconda3\lib\site-packages (from pandas) (1.19.2)
Requirement already satisfied: pytz>=2017.2 in c:\users\mirela\anaconda3\lib\site-packages (from pandas) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\mirela\anaconda3\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\mirela\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

# Pre-requisites

You can download the dataset for this tutorial https://www.kaggle.com/c/give-me-some-credit-20210326/data.
Make sure to have the following libraries installed before getting started: pandas, numpy, matplotlib, seaborn, scikit-learn.
Imports and reading the data frame
Run the following lines of code to import the necessary libraries and read the dataset:

In [2]:
import pandas as pd

In [3]:
# Read a comma-separated values (csv) file into DataFrame.
train = pd.read_csv('C:\\Users\\Mirela\\PycharmProjects\\GiveMeSomeCredit\\GiveMeSomeCredit\\cs-training.csv')
train

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
149995,149996,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149996,149997,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149997,149998,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149998,149999,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
149999,150000,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [4]:
# Renaming first column
train.rename(columns={'Unnamed: 0':'Id'}, 
                 inplace=True)

In [5]:
test = pd.read_csv('C:\\Users\\Mirela\\PycharmProjects\\GiveMeSomeCredit\\GiveMeSomeCredit\\cs-test.csv')
test

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,NaN,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0
1,2,NaN,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0
2,3,NaN,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0
3,4,NaN,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0
4,5,NaN,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
101498,101499,NaN,0.282653,24,0,0.068522,1400.0,5,0,0,0,0.0
101499,101500,NaN,0.922156,36,3,0.934217,7615.0,8,0,2,0,4.0
101500,101501,NaN,0.081596,70,0,836.000000,NaN,3,0,0,0,NaN
101501,101502,NaN,0.335457,56,0,3568.000000,NaN,8,0,2,1,3.0
101502,101503,NaN,0.441842,29,0,0.198918,5916.0,12,0,0,0,0.0

In [6]:
sampleEntry = pd.read_csv('C:\\Users\\Mirela\\PycharmProjects\\GiveMeSomeCredit\\GiveMeSomeCredit\\sampleEntry.csv')
sampleEntry

            Id  Probability
0            1     0.080807
1            2     0.040719
2            3     0.011968
3            4     0.067640
4            5     0.108264
...        ...          ...
101498  101499     0.045363
101499  101500     0.343775
101500  101501     0.006970
101501  101502     0.121994
101502  101503     0.044248

[101503 rows x 2 columns]

In [7]:
type(train)

pandas.core.frame.DataFrame

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Id                                    150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

I used to print a concise summary about a DataFrame including the index dtype and column dtypes, non-null values and memory usage.

In [9]:
# Fill na values appropriately
missing_replacements = train.mean()

train.fillna(missing_replacements, inplace=True)

train.isnull().sum()

Id                                      0
SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

In [10]:
train.describe()

,Id,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.500000e+05,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,75000.500000,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,43301.414527,0.249746,249.755371,14.771866,4.192781,2037.818523,1.288045e+04,5.145951,4.169304,1.129771,4.155179,1.100404
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.000000,0.029867,41.000000,0.000000,0.175074,3.903000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.000000,0.154181,52.000000,0.000000,0.366508,6.600000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,112500.250000,0.000000,0.559046,63.000000,0.000000,0.868254,7.400000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,150000.000000,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

I used the describe() method for calculating some statistical data like percentile, mean, and std of the numerical values of the Series or DataFrame. It analyses both numeric and object series and also the DataFrame column sets of mixed data types.

In [11]:
target = train['SeriousDlqin2yrs']
target

0         1
1         0
2         0
3         0
4         0
         ..
149995    0
149996    0
149997    0
149998    0
149999    0
Name: SeriousDlqin2yrs, Length: 150000, dtype: int64

In [12]:
data = train[['Id','RevolvingUtilizationOfUnsecuredLines','age','NumberOfTime30-59DaysPastDueNotWorse','DebtRatio','MonthlyIncome','NumberOfOpenCreditLinesAndLoans','NumberOfTimes90DaysLate','NumberRealEstateLoansOrLines','NumberOfTime60-89DaysPastDueNotWorse','NumberOfDependents']]
data

,Id,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.000000,13,0,6,0,2.0
1,2,0.957151,40,0,0.121876,2600.000000,4,0,0,0,1.0
2,3,0.658180,38,1,0.085113,3042.000000,2,1,0,0,0.0
3,4,0.233810,30,0,0.036050,3300.000000,5,0,0,0,0.0
4,5,0.907239,49,1,0.024926,63588.000000,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149995,149996,0.040674,74,0,0.225131,2100.000000,4,0,1,0,0.0
149996,149997,0.299745,44,0,0.716562,5584.000000,4,0,1,0,2.0
149997,149998,0.246044,58,0,3870.000000,6670.221237,18,0,1,0,0.0
149998,149999,0.000000,30,0,0.000000,5716.000000,4,0,0,0,0.0
149999,150000,0.850283,64,0,0.249908,8158.000000,8,0,2,0,0.0

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [14]:
lr = LogisticRegression()
scores = cross_val_score(lr, data, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93326 accuracy with a standard deviation of 0.00018

The simplest way to use cross-validation is to call the cross_val_score helper function on the estimator and the dataset.

# Standardizing variables

In [15]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
ss = StandardScaler()
data1 = ss.fit_transform(data)
data

,Id,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,0.766127,45,2,0.802982,9120.000000,13,0,6,0,2.0
1,2,0.957151,40,0,0.121876,2600.000000,4,0,0,0,1.0
2,3,0.658180,38,1,0.085113,3042.000000,2,1,0,0,0.0
3,4,0.233810,30,0,0.036050,3300.000000,5,0,0,0,0.0
4,5,0.907239,49,1,0.024926,63588.000000,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149995,149996,0.040674,74,0,0.225131,2100.000000,4,0,1,0,0.0
149996,149997,0.299745,44,0,0.716562,5584.000000,4,0,1,0,2.0
149997,149998,0.246044,58,0,3870.000000,6670.221237,18,0,1,0,0.0
149998,149999,0.000000,30,0,0.000000,5716.000000,4,0,0,0,0.0
149999,150000,0.850283,64,0,0.249908,8158.000000,8,0,2,0,0.0

First, lets standardize all variables in the dataset to get them around the same scale.
Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual features do not more or less look like standard normally distributed data.

In [16]:
data1

array([[-1.73203926, -0.02115001, -0.49385982, ...,  4.40954554,
        -0.05785249,  1.12938692],
       [-1.73201617, -0.02038516, -0.83234222, ..., -0.90128301,
        -0.05785249,  0.22062674],
       [-1.73199307, -0.02158222, -0.96773518, ..., -0.90128301,
        -0.05785249, -0.68813345],
       ...,
       [ 1.73199307, -0.02323239,  0.38619443, ..., -0.01614492,
        -0.05785249, -0.68813345],
       [ 1.73201617, -0.02421753, -1.50930703, ..., -0.90128301,
        -0.05785249, -0.68813345],
       [ 1.73203926, -0.02081306,  0.79237332, ...,  0.86899317,
        -0.05785249, -0.68813345]])

In [17]:
mm = MinMaxScaler()
data2 = mm.fit_transform(data)
data2

array([[0.00000000e+00, 1.51085945e-05, 4.12844037e-01, ...,
        1.11111111e-01, 0.00000000e+00, 1.00000000e-01],
       [6.66671111e-06, 1.88757399e-05, 3.66972477e-01, ...,
        0.00000000e+00, 0.00000000e+00, 5.00000000e-02],
       [1.33334222e-05, 1.29798087e-05, 3.48623853e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.99986667e-01, 4.85217161e-06, 5.32110092e-01, ...,
        1.85185185e-02, 0.00000000e+00, 0.00000000e+00],
       [9.99993333e-01, 0.00000000e+00, 2.75229358e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 1.67682210e-05, 5.87155963e-01, ...,
        3.70370370e-02, 0.00000000e+00, 0.00000000e+00]])

This estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one.

# Cross-validation

Cross-validation means evaluating estimator performance
The simplest way to use cross-validation is to call the cross_val_score helper function on the estimator and the dataset.

In [18]:
scores=cross_val_score(lr, data1, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93384 accuracy with a standard deviation of 0.00043

In [19]:
scores=cross_val_score(lr, data2, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93331 accuracy with a standard deviation of 0.00018

In [20]:
from sklearn.neighbors import KNeighborsClassifier
kn = KNeighborsClassifier()
cross_val_score(kn, data1, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93331 accuracy with a standard deviation of 0.00018

In [21]:
from sklearn.naive_bayes import GaussianNB
gn = GaussianNB()
cross_val_score(gn, data1, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93331 accuracy with a standard deviation of 0.00018

In [22]:
dt = DecisionTreeClassifier()
scores=cross_val_score(dt, data1, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.73470 accuracy with a standard deviation of 0.31147

Looking at the 4 estimators I used must be said that the dt estimator performs the worst in this case.

# Feature importances

In [23]:
dt.fit(data1, target)
dt.feature_importances_

array([0.16143006, 0.15755632, 0.10473761, 0.03452218, 0.14731133,
       0.11847628, 0.06743854, 0.12733455, 0.02596568, 0.02226182,
       0.03296563])

A decision tree classifier will be fitted to compute the feature importances.
Feature importances are provided by the fitted attribute feature_importances_ and they are computed as the mean and standard deviation of accumulation of the impurity decrease within each tree.

In [24]:
dt.feature_importances_ > 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [25]:
dt.feature_importances_ > 0.04

array([ True,  True,  True, False,  True,  True,  True,  True, False,
       False, False])

In [26]:
data1[:, dt.feature_importances_ > 0.04]

array([[-1.73203926e+00, -2.11500119e-02, -4.93859818e-01, ...,
         1.90194266e-01,  8.83656911e-01, -6.37934373e-02],
       [-1.73201617e+00, -2.03851633e-02, -8.32342222e-01, ...,
        -3.16001083e-01, -8.65296784e-01, -6.37934373e-02],
       [-1.73199307e+00, -2.15822221e-02, -9.67735183e-01, ...,
        -2.81685386e-01, -1.25395316e+00,  1.76055560e-01],
       ...,
       [ 1.73199307e+00, -2.32323872e-02,  3.86194432e-01, ...,
        -2.11832203e-16,  1.85529785e+00, -6.37934373e-02],
       [ 1.73201617e+00, -2.42175301e-02, -1.50930703e+00, ...,
        -7.40831828e-02, -8.65296784e-01, -6.37934373e-02],
       [ 1.73203926e+00, -2.08130557e-02,  7.92373317e-01, ...,
         1.15507161e-01, -8.79840306e-02, -6.37934373e-02]])

In [27]:
data1[:, dt.feature_importances_ > 0.04].shape

(150000, 7)

In [28]:
scores=cross_val_score(lr, data1[:, dt.feature_importances_ > 0.04], target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93332 accuracy with a standard deviation of 0.00020

After calculating the feature importances., I chose the value to be greater than 0.04 and got a new data set called data3.

In [52]:
data3 = data1[:, dt.feature_importances_ > 0.04]

In [53]:
data3

array([[-1.73203926e+00, -2.11500119e-02, -4.93859818e-01, ...,
         1.90194266e-01,  8.83656911e-01, -6.37934373e-02],
       [-1.73201617e+00, -2.03851633e-02, -8.32342222e-01, ...,
        -3.16001083e-01, -8.65296784e-01, -6.37934373e-02],
       [-1.73199307e+00, -2.15822221e-02, -9.67735183e-01, ...,
        -2.81685386e-01, -1.25395316e+00,  1.76055560e-01],
       ...,
       [ 1.73199307e+00, -2.32323872e-02,  3.86194432e-01, ...,
        -2.11832203e-16,  1.85529785e+00, -6.37934373e-02],
       [ 1.73201617e+00, -2.42175301e-02, -1.50930703e+00, ...,
        -7.40831828e-02, -8.65296784e-01, -6.37934373e-02],
       [ 1.73203926e+00, -2.08130557e-02,  7.92373317e-01, ...,
         1.15507161e-01, -8.79840306e-02, -6.37934373e-02]])

In [30]:
scores=cross_val_score(gn, data3, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93325 accuracy with a standard deviation of 0.00031

In [31]:
scores=cross_val_score(kn, data3, target)
print("%0.5f accuracy with a standard deviation of %0.5f" % (scores.mean(), scores.std()))

0.93323 accuracy with a standard deviation of 0.00139

In [32]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [33]:
trd, tsd, trt, tst = train_test_split(data3, target)

Split arrays or matrices into random train and test subsets

# Confusion matrix

Confusion matrix
Split arrays or matrices into random train and test subsets. After that a logistic regression estimator will be fitted to compute confusion matrix to evaluate the accuracy of a classification.

In [34]:
lr.fit(trd, trt)

LogisticRegression()

In [35]:
confusion_matrix(lr.predict(tsd), tst)

array([[34969,  2473],
       [   22,    36]], dtype=int64)

Compute confusion matrix to evaluate the accuracy of a classification.

In [36]:
lr.predict_proba(tsd)[:,0]

array([0.96621062, 0.93352536, 0.96611406, ..., 0.92598014, 0.95411382,
       0.90470569])

In [37]:
confusion_matrix(lr.predict_proba(tsd)[:,0]<0.7, tst)

array([[34969,  2473],
       [   22,    36]], dtype=int64)

A confusion matrix is a table that is often used to describe the performance of a classification model (or "classifier") on a set of test data for which the true values are known.

TN = 34983 : We predicted no, and they don't have the financial distress

FN = 2442 : We predicted no, but they actually do have the financial distress. (Also known as a "Type II error.")

FP = 34: We predicted yes, but they don't actually have the financial distress. (Also known as a "Type I error.")

TP =41 : These are cases in which we predicted yes (they have the financial distress), and they do have the financial distress.

Accuracy: Overall, how often is the classifier correct?
(TP+TN)/total

Precision: When it predicts yes, how often is it correct?
TP/predicted yes

True Positive Rate: When it's actually yes, how often does it predict yes?

TP/actual yes 
also known as "Sensitivity" or "Recall"

f1 score = 2*Recall*Precision/ Recall + Precision

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(tst, lr.predict(tsd))

0.9334666666666667

In [39]:
from sklearn.metrics import precision_score
precision_score(tst,lr.predict(tsd))

0.6206896551724138

In [40]:
from sklearn.metrics import recall_score
recall_score(tst, lr.predict(tsd))

0.01434834595456357

In [41]:
from sklearn.metrics import f1_score
f1_score(tst, lr.predict(tsd))

0.02804830541488118

In [42]:
# Renaming first column
test.rename(columns={'Unnamed: 0':'Id'}, 
                 inplace=True)

In [43]:
type(test)

pandas.core.frame.DataFrame

In [56]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101503 entries, 0 to 101502
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Id                                    101503 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  101503 non-null  float64
 2   age                                   101503 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  101503 non-null  int64
 4   DebtRatio                             101503 non-null  float64
 5   MonthlyIncome                         101503 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       101503 non-null  int64
 7   NumberOfTimes90DaysLate               101503 non-null  int64
 8   NumberRealEstateLoansOrLines          101503 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  101503 non-null  int64
 10  NumberOfDependents                    101503 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 8.5 MB

In [97]:
# Fill na values appropriately
missing_replacements = test.mean()

test.fillna(missing_replacements, inplace=True)

test.isnull().sum()

Id                                      0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
dtype: int64

In [98]:
import numpy as np
test=test[['Id','RevolvingUtilizationOfUnsecuredLines','age','NumberOfTime30-59DaysPastDueNotWorse','MonthlyIncome','NumberOfOpenCreditLinesAndLoans','NumberOfTimes90DaysLate']]
lr_proba = lr.predict_proba(test)[:,0]
lr_proba
ids = np.arange(1,101504)
lr_submission = pd.DataFrame( {'Id': ids, 'Probability': lr_proba})
lr_submission.to_csv("submission3.csv", index=False)

# Conclusion

We have successfully use cross-validation to evaluate some estimators performance.  We also explored feature importances, and analysed the behaviour of new dataset we ve obtained.
Finally, we took a look at confusion matrix that describe the performance of a classification model.